"""renomeia averia para avaria

Revision ID: 4842680f7abd
Revises: 0008_drv_claims
Create Date: 2026-04-11 23:47:34.892549
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4842680f7abd'
down_revision = '0008_drv_claims'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor_user', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity_type', table_name='audit_logs')
    op.drop_constraint('claims_created_by_fkey', 'claims', type_='foreignkey')
    op.create_foreign_key(None, 'claims', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('drivers', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.CITEXT(),
               existing_nullable=True)
    op.alter_column('drivers', 'cnh_categoria',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', name='driver_license_category'),
               nullable=False)
    op.drop_index('idx_history_vehicle', table_name='location_history')
    op.drop_index('idx_location_history_allocation', table_name='location_history')
    op.drop_index('uq_location_history_active', table_name='location_history', postgresql_where='(end_date IS NULL)')
    op.create_index(op.f('ix_location_history_allocation_id'), 'location_history', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_location_history_vehicle_id'), 'location_history', ['vehicle_id'], unique=False)
    op.drop_index('idx_master_allocations_department', table_name='master_allocations')
    op.create_index(op.f('ix_master_allocations_department_id'), 'master_allocations', ['department_id'], unique=False)
    op.drop_index('idx_master_departments_org', table_name='master_departments')
    op.create_index(op.f('ix_master_departments_organization_id'), 'master_departments', ['organization_id'], unique=False)
    op.drop_index('idx_master_organizations_name', table_name='master_organizations')
    op.drop_constraint('uq_master_organizations_name', 'master_organizations', type_='unique')
    op.create_index(op.f('ix_master_organizations_name'), 'master_organizations', ['name'], unique=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('idx_possession_driver_id', table_name='vehicle_possession')
    op.create_index(op.f('ix_vehicle_possession_driver_id'), 'vehicle_possession', ['driver_id'], unique=False)
    op.drop_constraint('fk_vehicle_possession_driver', 'vehicle_possession', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_possession', 'drivers', ['driver_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index('idx_vehicles_chassis_number', table_name='vehicles')
    op.drop_index('idx_vehicles_plate', table_name='vehicles')
    op.drop_index('idx_vehicles_status', table_name='vehicles')
    op.drop_constraint('uq_vehicles_plate', 'vehicles', type_='unique')
    op.create_index(op.f('ix_vehicles_chassis_number'), 'vehicles', ['chassis_number'], unique=True)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_chassis_number'), table_name='vehicles')
    op.create_unique_constraint('uq_vehicles_plate', 'vehicles', ['plate'])
    op.create_index('idx_vehicles_status', 'vehicles', ['status'], unique=False)
    op.create_index('idx_vehicles_plate', 'vehicles', ['plate'], unique=False)
    op.create_index('idx_vehicles_chassis_number', 'vehicles', ['chassis_number'], unique=True)
    op.drop_constraint(None, 'vehicle_possession', type_='foreignkey')
    op.create_foreign_key('fk_vehicle_possession_driver', 'vehicle_possession', 'drivers', ['driver_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_vehicle_possession_driver_id'), table_name='vehicle_possession')
    op.create_index('idx_possession_driver_id', 'vehicle_possession', ['driver_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_master_organizations_name'), table_name='master_organizations')
    op.create_unique_constraint('uq_master_organizations_name', 'master_organizations', ['name'])
    op.create_index('idx_master_organizations_name', 'master_organizations', ['name'], unique=False)
    op.drop_index(op.f('ix_master_departments_organization_id'), table_name='master_departments')
    op.create_index('idx_master_departments_org', 'master_departments', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_master_allocations_department_id'), table_name='master_allocations')
    op.create_index('idx_master_allocations_department', 'master_allocations', ['department_id'], unique=False)
    op.drop_index(op.f('ix_location_history_vehicle_id'), table_name='location_history')
    op.drop_index(op.f('ix_location_history_allocation_id'), table_name='location_history')
    op.create_index('uq_location_history_active', 'location_history', ['vehicle_id'], unique=True, postgresql_where='(end_date IS NULL)')
    op.create_index('idx_location_history_allocation', 'location_history', ['allocation_id'], unique=False)
    op.create_index('idx_history_vehicle', 'location_history', ['vehicle_id'], unique=False)
    op.alter_column('drivers', 'cnh_categoria',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', name='driver_license_category'),
               nullable=True)
    op.alter_column('drivers', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.create_foreign_key('claims_created_by_fkey', 'claims', 'users', ['created_by'], ['id'])
    op.create_index('idx_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_actor_user', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
